name: Automated releases
on:
  schedule:
    # "At 00:00 on Sunday" (https://crontab.guru/once-a-week)
    - cron: "* * * * *"

jobs:
  release-pr:
    runs-on: ubuntu-latest
    outputs:
      did-create-pr: ${{ steps.release.outputs.did-create-pr }}
      new-version: ${{ steps.release.outputs.new-version }}
    steps:
      - uses: simple-icons/release-action@master
        id: release
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  version-bump:
    runs-on: ubuntu-latest
    needs: release-pr
    if: needs.release-pr.outputs.did-create-pr == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Ensure we are checked out on the develop branch
          ref: develop
      - run: echo "${{ needs.release-pr.outputs.new-version }}"
